### ISSUE TITLE
Ticket linking

### ISSUE THREAD

**Issue by chasinglogic** [praelatus/praelatus#15]
Tickets should be able to be linked to one another to show dependencies or other kinds of relationships

**Comment by link867** [comment]
1. Create a migration
2. Add to the Store interface for storing and retrieving 
3. Add to the test where there is a mock store
4. Implement those methods for the postgresql store
5. Add links to the database seeding 
6. Write integration tests for postgres store
7. Create endpoints for managing links ( API )
8. Add to get ticket endpoint so tickets can be preloaded
9. Write tests for the endpoints
10. That's pretty much it
