### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by chasinglogic** [praelatus/praelatus#16]
Tickets should be able to have "sub tickets" called tasks, need to discuss what functionality they would require (i.e. should they be identical to tickets just with a special link or have their own rules etc.)

**Comment by chasinglogic** [comment]
@lionize thoughts on this?

**Comment by chasinglogic** [comment]
I'm looking to start implementing this feature and would like advice on whether we should just treat them as tickets and have special "links" or treat them differently, additionally how would you expect the JSON to look on a ticket which has these?

**Comment by lionize** [comment]
Treat them as tickets. They deserve to be treated as first-class citizens in case users want to make them up with additional information or flags or whatever. I'd just make a `subtasks` or `subtickets` field on a ticket and supply the children resources that way.

**Comment by chasinglogic** [comment]
would you then treat normally linked tickets differently?

**Comment by lionize** [comment]
What do you mean?

**Comment by chasinglogic** [comment]
So we're going to support ticket links showing dependencies and other relationships take a look at #15 and it's partially implemented on Ryan's fork ticket_linking branch: https://github.com/link867/praelatus/tree/ticket_linking

**Comment by link867** [comment]
Don't have to make a model
