### ISSUE TITLE
can you provide function list, thanks a lot

### ISSUE THREAD

**Issue by jacobluo** [praelatus/praelatus#76]
can you provide function list, thanks a lot

**Comment by chasinglogic** [comment]
Hey @jacobluo I'm not sure what you mean exactly but this project isn't really maintained any longer, we've left it here in case we decide to revisit it but we aren't actively developing it.

**Comment by lionize** [comment]
Hi @jacobluo, we've decided to actively develop this again. :) 

What do you mean by a function list?

**Comment by chasinglogic** [comment]
@jacobluo if we don't hear back in another week we will close this issue as inactive
